countdown: 10800
raninterval: 10
ranstay: 1
ranamount: 2
maintenance: false
allowedmaterials:
 - ANVIL
 - APPLE
 - ARROW
 - BAKED_POTATO
 - BED
 - BLAZE_POWDER
 - BLAZE_ROD
 - BOAT
 - BONE
 - BOOK
 - BOOK_AND_QUILL
 - BOOKSHELF
 - BOW
 - BOWL
 - BREAD
 - BRICK
 - BROWN_MUSHROOM
 - BUCKET
 - CACTUS
 - CAKE
 - CARPET
 - CARROT
 - CAULDRON
 - CHAINMAIL_BOOTS
 - CHAINMAIL_CHESTPLATE
 - CHAINMAIL_HELMET
 - CHAINMAIL_LEGGINGS
 - CHEST
 - CLAY
 - CLAY_BALL
 - CLAY_BRICK
 - COAL
 - COAL_BLOCK
 - COAL_ORE
 - COBBLE_WALL
 - COBBLESTONE
 - COCOA
 - COMPASS
 - COOKED_BEEF
 - COOKED_CHICKEN
 - COOKED_FISH
 - COOKIE
 - CROPS
 - DAYLIGHT_DETECTOR
 - DIAMOND
 - DIAMOND_AXE
 - DIAMOND_BARDING
 - DIAMOND_BLOCK
 - DIAMOND_BOOTS
 - DIAMOND_CHESTPLATE
 - DIAMOND_HELMET
 - DIAMOND_HOE
 - DIAMOND_LEGGINGS
 - DIAMOND_ORE
 - DIAMOND_PICKAXE
 - DIAMOND_SPADE
 - DIAMOND_SWORD
 - DIRT
 - DISPENSER
 - DROPPER
 - EGG
 - EMERALD
 - EMERALD_BLOCK
 - EMERALD_ORE
 - EMPTY_MAP
 - ENCHANTMENT_TABLE
 - ENDER_CHEST
 - ENDER_PEARL
 - ENDER_STONE
 - EXP_BOTTLE
 - EXPLOSIVE_MINECART
 - EYE_OF_ENDER
 - FEATHER
 - FENCE
 - FENCE_GATE
 - FERMENTED_SPIDER_EYE
 - FISHING_ROD
 - FLINT
 - FLINT_AND_STEEL
 - FLOWER_POT
 - FURNACE
 - GHAST_TEAR
 - GLASS
 - GLASS_BOTTLE
 - GLOWSTONE
 - GLOWSTONE_DUST
 - GOLD_AXE
 - GOLD_BARDING
 - GOLD_BLOCK
 - GOLD_BOOTS
 - GOLD_CHESTPLATE
 - GOLD_HELMET
 - GOLD_HOE
 - GOLD_INGOT
 - GOLD_LEGGINGS
 - GOLD_NUGGET
 - GOLD_ORE
 - GOLD_PICKAXE
 - GOLD_PLATE
 - GOLD_SPADE
 - GOLD_SWORD
 - GOLDEN_APPLE
 - GOLDEN_CARROT
 - GRASS
 - GRAVEL
 - GRILLED_PORK
 - HARD_CLAY
 - HAY_BLOCK
 - HOPPER
 - HOPPER_MINECART
 - ICE
 - INK_SACK
 - IRON_AXE
 - IRON_BARDING
 - IRON_BLOCK
 - IRON_BOOTS
 - IRON_CHESTPLATE
 - IRON_DOOR
 - IRON_DOOR_BLOCK
 - IRON_FENCE
 - IRON_HELMET
 - IRON_HOE
 - IRON_INGOT
 - IRON_LEGGINGS
 - IRON_ORE
 - IRON_PICKAXE
 - IRON_PLATE
 - IRON_SPADE
 - IRON_SWORD
 - ITEM_FRAME
 - JACK_O_LANTERN
 - JUKEBOX
 - LADDER
 - LAPIS_BLOCK
 - LAPIS_ORE
 - LAVA_BUCKET
 - LEASH
 - LEATHER
 - LEATHER_BOOTS
 - LEATHER_CHESTPLATE
 - LEATHER_HELMET
 - LEATHER_LEGGINGS
 - LEAVES
 - LEVER
 - LOCKED_CHEST
 - LOG
 - LONG_GRASS
 - MAGMA_CREAM
 - MELON
 - MELON_BLOCK
 - MELON_SEEDS
 - MELON_STEM
 - MILK_BUCKET
 - MINECART
 - MOSSY_COBBLESTONE
 - MUSHROOM_SOUP
 - MYCEL
 - NAME_TAG
 - NETHER_BRICK
 - NETHER_BRICK_ITEM
 - NETHER_FENCE
 - NETHER_STALK
 - NETHER_STAR
 - NETHER_WARTS
 - NETHERRACK
 - NOTE_BLOCK
 - OBSIDIAN
 - PAINTING
 - PAPER
 - POISONOUS_POTATO
 - PORK
 - POTATO
 - POTION
 - POWERED_MINECART
 - POWERED_RAIL
 - PUMPKIN
 - PUMPKIN_PIE
 - PUMPKIN_SEEDS
 - QUARTZ
 - QUARTZ_BLOCK
 - QUARTZ_ORE
 - RAILS
 - RAW_BEEF
 - RAW_CHICKEN
 - RAW_FISH
 - RED_MUSHROOM
 - RED_ROSE
 - REDSTONE
 - REDSTONE_BLOCK
 - REDSTONE_COMPARATOR
 - REDSTONE_ORE
 - REDSTONE_WIRE
 - ROTTEN_FLESH
 - SADDLE
 - SAND
 - SANDSTONE
 - SAPLING
 - SEEDS
 - SHEARS
 - SIGN
 - SLIME_BALL
 - SMOOTH_BRICK
 - SNOW
 - SNOW_BALL
 - SNOW_BLOCK
 - SOIL
 - SOUL_SAND
 - SPECKLED_MELON
 - SPIDER_EYE
 - STAINED_CLAY
 - STICK
 - STONE
 - STONE_AXE
 - STONE_BUTTON
 - STONE_HOE
 - STONE_PICKAXE
 - STONE_PLATE
 - STONE_SPADE
 - STONE_SWORD
 - STORAGE_MINECART
 - STRING
 - SUGAR
 - SUGAR_CANE
 - SULPHUR
 - THIN_GLASS
 - TNT
 - TORCH
 - TRAP_DOOR
 - TRAPPED_CHEST
 - VINE
 - WATCH
 - WATER_BUCKET
 - WATER_LILY
 - WEB
 - WHEAT
 - WOOD
 - WOOD_AXE
 - WOOD_BUTTON
 - WOOD_DOOR
 - WOOD_DOUBLE_STEP
 - WOOD_HOE
 - WOOD_PICKAXE
 - WOOD_PLATE
 - WOOD_SPADE
 - WOOD_STEP
 - WOOD_SWORD
 - WOODEN_DOOR
 - WOOL
 - WORKBENCH
 - YELLOW_FLOWER