countdown: 10800
raninterval: 10
ranstay: 1
ranamount: 2
maintenance: false
materials:
  ANVIL                : 0.5
  APPLE                : 0.5
  ARROW                : 0.5
  BAKED_POTATO         : 0.5
  BED                  : 0.5
  BLAZE_POWDER         : 0.5
  BLAZE_ROD            : 0.5
  BOAT                 : 0.5
  BONE                 : 0.5
  BOOK                 : 0.5
  BOOK_AND_QUILL       : 0.5
  BOOKSHELF            : 0.5
  BOW                  : 0.5
  BOWL                 : 0.5
  BREAD                : 0.5
  BRICK                : 0.5
  BROWN_MUSHROOM       : 0.5
  BUCKET               : 0.5
  CACTUS               : 0.5
  CAKE                 : 0.5
  CARPET               : 0.5
  CARROT               : 0.5
  CAULDRON             : 0.5
  CHAINMAIL_BOOTS      : 0.5
  CHAINMAIL_CHESTPLATE : 0.5
  CHAINMAIL_HELMET     : 0.5
  CHAINMAIL_LEGGINGS   : 0.5
  CHEST                : 0.5
  CLAY                 : 0.5
  CLAY_BALL            : 0.5
  CLAY_BRICK           : 0.5
  COAL                 : 0.5
  COAL_BLOCK           : 0.5
  COAL_ORE             : 0.5
  COBBLE_WALL          : 0.5
  COBBLESTONE          : 0.5
  COCOA                : 0.5
  COMPASS              : 0.5
  COOKED_BEEF          : 0.5
  COOKED_CHICKEN       : 0.5
  COOKED_FISH          : 0.5
  COOKIE               : 0.5
  CROPS                : 0.5
  DAYLIGHT_DETECTOR    : 0.5
  DIAMOND              : 0.5
  DIAMOND_AXE          : 0.5
  DIAMOND_BARDING      : 0.5
  DIAMOND_BLOCK        : 0.5
  DIAMOND_BOOTS        : 0.5
  DIAMOND_CHESTPLATE   : 0.5
  DIAMOND_HELMET       : 0.5
  DIAMOND_HOE          : 0.5
  DIAMOND_LEGGINGS     : 0.5
  DIAMOND_ORE          : 0.5
  DIAMOND_PICKAXE      : 0.5
  DIAMOND_SPADE        : 0.5
  DIAMOND_SWORD        : 0.5
  DIRT                 : 0.5
  DISPENSER            : 0.5
  DROPPER              : 0.5
  EGG                  : 0.5
  EMERALD              : 0.5
  EMERALD_BLOCK        : 0.5
  EMERALD_ORE          : 0.5
  EMPTY_MAP            : 0.5
  ENCHANTMENT_TABLE    : 0.5
  ENDER_CHEST          : 0.5
  ENDER_PEARL          : 0.5
  ENDER_STONE          : 0.5
  EXP_BOTTLE           : 0.5
  EXPLOSIVE_MINECART   : 0.5
  EYE_OF_ENDER         : 0.5
  FEATHER              : 0.5
  FENCE                : 0.5
  FENCE_GATE           : 0.5
  FERMENTED_SPIDER_EYE : 0.5
  FISHING_ROD          : 0.5
  FLINT                : 0.5
  FLINT_AND_STEEL      : 0.5
  FLOWER_POT           : 0.5
  FURNACE              : 0.5
  GHAST_TEAR           : 0.5
  GLASS                : 0.5
  GLASS_BOTTLE         : 0.5
  GLOWSTONE            : 0.5
  GLOWSTONE_DUST       : 0.5
  GOLD_AXE             : 0.5
  GOLD_BARDING         : 0.5
  GOLD_BLOCK           : 0.5
  GOLD_BOOTS           : 0.5
  GOLD_CHESTPLATE      : 0.5
  GOLD_HELMET          : 0.5
  GOLD_HOE             : 0.5
  GOLD_INGOT           : 0.5
  GOLD_LEGGINGS        : 0.5
  GOLD_NUGGET          : 0.5
  GOLD_ORE             : 0.5
  GOLD_PICKAXE         : 0.5
  GOLD_PLATE           : 0.5
  GOLD_SPADE           : 0.5
  GOLD_SWORD           : 0.5
  GOLDEN_APPLE         : 0.5
  GOLDEN_CARROT        : 0.5
  GRASS                : 0.5
  GRAVEL               : 0.5
  GRILLED_PORK         : 0.5
  HARD_CLAY            : 0.5
  HAY_BLOCK            : 0.5
  HOPPER               : 0.5
  HOPPER_MINECART      : 0.5
  ICE                  : 0.5
  INK_SACK             : 0.5
  IRON_AXE             : 0.5
  IRON_BARDING         : 0.5
  IRON_BLOCK           : 0.5
  IRON_BOOTS           : 0.5
  IRON_CHESTPLATE      : 0.5
  IRON_DOOR            : 0.5
  IRON_DOOR_BLOCK      : 0.5
  IRON_FENCE           : 0.5
  IRON_HELMET          : 0.5
  IRON_HOE             : 0.5
  IRON_INGOT           : 0.5
  IRON_LEGGINGS        : 0.5
  IRON_ORE             : 0.5
  IRON_PICKAXE         : 0.5
  IRON_PLATE           : 0.5
  IRON_SPADE           : 0.5
  IRON_SWORD           : 0.5
  ITEM_FRAME           : 0.5
  JACK_O_LANTERN       : 0.5
  JUKEBOX              : 0.5
  LADDER               : 0.5
  LAPIS_BLOCK          : 0.5
  LAPIS_ORE            : 0.5
  LAVA_BUCKET          : 0.5
  LEASH                : 0.5
  LEATHER              : 0.5
  LEATHER_BOOTS        : 0.5
  LEATHER_CHESTPLATE   : 0.5
  LEATHER_HELMET       : 0.5
  LEATHER_LEGGINGS     : 0.5
  LEAVES               : 0.5
  LEVER                : 0.5
  LOCKED_CHEST         : 0.5
  LOG                  : 0.5
  LONG_GRASS           : 0.5
  MAGMA_CREAM          : 0.5
  MELON                : 0.5
  MELON_BLOCK          : 0.5
  MELON_SEEDS          : 0.5
  MELON_STEM           : 0.5
  MILK_BUCKET          : 0.5
  MINECART             : 0.5
  MOSSY_COBBLESTONE    : 0.5
  MUSHROOM_SOUP        : 0.5
  MYCEL                : 0.5
  NAME_TAG             : 0.5
  NETHER_BRICK         : 0.5
  NETHER_BRICK_ITEM    : 0.5
  NETHER_FENCE         : 0.5
  NETHER_STALK         : 0.5
  NETHER_STAR          : 0.5
  NETHER_WARTS         : 0.5
  NETHERRACK           : 0.5
  NOTE_BLOCK           : 0.5
  OBSIDIAN             : 0.5
  PAINTING             : 0.5
  PAPER                : 0.5
  POISONOUS_POTATO     : 0.5
  PORK                 : 0.5
  POTATO               : 0.5
  POTION               : 0.5
  POWERED_MINECART     : 0.5
  POWERED_RAIL         : 0.5
  PUMPKIN              : 0.5
  PUMPKIN_PIE          : 0.5
  PUMPKIN_SEEDS        : 0.5
  QUARTZ               : 0.5
  QUARTZ_BLOCK         : 0.5
  QUARTZ_ORE           : 0.5
  RAILS                : 0.5
  RAW_BEEF             : 0.5
  RAW_CHICKEN          : 0.5
  RAW_FISH             : 0.5
  RED_MUSHROOM         : 0.5
  RED_ROSE             : 0.5
  REDSTONE             : 0.5
  REDSTONE_BLOCK       : 0.5
  REDSTONE_COMPARATOR  : 0.5
  REDSTONE_ORE         : 0.5
  REDSTONE_WIRE        : 0.5
  ROTTEN_FLESH         : 0.5
  SADDLE               : 0.5
  SAND                 : 0.5
  SANDSTONE            : 0.5
  SAPLING              : 0.5
  SEEDS                : 0.5
  SHEARS               : 0.5
  SIGN                 : 0.5
  SLIME_BALL           : 0.5
  SMOOTH_BRICK         : 0.5
  SNOW                 : 0.5
  SNOW_BALL            : 0.5
  SNOW_BLOCK           : 0.5
  SOIL                 : 0.5
  SOUL_SAND            : 0.5
  SPECKLED_MELON       : 0.5
  SPIDER_EYE           : 0.5
  STAINED_CLAY         : 0.5
  STICK                : 0.5
  STONE                : 0.5
  STONE_AXE            : 0.5
  STONE_BUTTON         : 0.5
  STONE_HOE            : 0.5
  STONE_PICKAXE        : 0.5
  STONE_PLATE          : 0.5
  STONE_SPADE          : 0.5
  STONE_SWORD          : 0.5
  STORAGE_MINECART     : 0.5
  STRING               : 0.5
  SUGAR                : 0.5
  SUGAR_CANE           : 0.5
  SULPHUR              : 0.5
  THIN_GLASS           : 0.5
  TNT                  : 0.5
  TORCH                : 0.5
  TRAP_DOOR            : 0.5
  TRAPPED_CHEST        : 0.5
  VINE                 : 0.5
  WATCH                : 0.5
  WATER_BUCKET         : 0.5
  WATER_LILY           : 0.5
  WEB                  : 0.5
  WHEAT                : 0.5
  WOOD                 : 0.5
  WOOD_AXE             : 0.5
  WOOD_BUTTON          : 0.5
  WOOD_DOOR            : 0.5
  WOOD_DOUBLE_STEP     : 0.5
  WOOD_HOE             : 0.5
  WOOD_PICKAXE         : 0.5
  WOOD_PLATE           : 0.5
  WOOD_SPADE           : 0.5
  WOOD_STEP            : 0.5
  WOOD_SWORD           : 0.5
  WOODEN_DOOR          : 0.5
  WOOL                 : 0.5
  WORKBENCH            : 0.5
  YELLOW_FLOWER        : 0.5